function figNumber=updnarrow;
% Sets the current figure pointer to the updwn arrow.
%   figNumber=Wupdnarrow will set the current figure's pointer
%   to a watch.
%
%   See also WATCHOFF.

% If there are no windows open, just set figNumber to a flag value.
o=NaN;
waitsymbol = [ ...
      o o o 1 1 1 o o o o o o o o o o, ...
      o o 1 1 1 1 1 o o o o o o o o o, ...
      o 1 1 1 1 1 1 o o o o o o o o o, ...
      1 1 o o o 1 1 1 o o o o o o o o, ...
      1 o o o o 1 1 1 o o o o o o o o, ...
      o o o o o 1 1 1 o o o o o o o o, ...
      o o o o o 1 1 1 o o o o o o o o, ...
      o o o o o 1 1 1 o o o o o o o o, ...
      o o o o o 1 1 1 o o o o o o o o, ...
      o o o o o 1 1 1 o o o o o o o o, ...
      o o o o o 1 1 1 o o o o 1 o o o, ...
      o o o o o 1 1 1 o o o 1 1 o o o, ...
      o o o o o 1 1 1 o o 1 1 o o o o, ...
      o o o o o 1 1 1 1 1 1 o o o o o, ...
      o o o o o 1 1 1 1 1 1 o o o o o, ...
      o o o o o 1 1 1 1 1 o o o o o o ];

waitsymbol = rot90(reshape(waitsymbol, 16, 16));
   

if isempty(get(0,'Children')),
    figNumber=NaN;
else
    figNumber=gcf;
    set(figNumber, 'PointerShapeCData', waitsymbol);
    set(figNumber,'Pointer','custom');
end
